name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pass hook secrets
      shell: bash
      env:
        REPORTHOOK: ${{ secrets.REPORTHOOK }}
        ERRORHOOK: ${{ secrets.ERRORHOOK }}
      run: |
        echo 'reportHook = $REPORTHOOK' >> config.py
        echo 'errorHook = $ERRORHOOK' >> config.py

    - name: Set up QEMU
      run: cat config.py
