name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Add report webhook
      run: echo 'reportHook = ${{ secrets.REPORTHOOK }}' >> config.py

    - name: Add error webhook
      run: echo 'errorHook = ${{ secrets.ERRORHOOK }}' >> config.py

    - name: Set up QEMU
      run: cat config.py
