name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add report webhook
      run: echo ${{ secrets.REPORTHOOK }} >> config.py

    - name: Add error webhook
      run: echo ${{ secrets.ERRORHOOK }} >> config.py

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Show config settings
      run: cat config.py
