name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Add report webhook
      run: echo 'reportHook = ${{ secrets.REPORTHOOK }}' >> config.py

    - name: Add error webhook
      run: echo 'errorHook = ${{ secrets.ERRORHOOK }}' >> config.py

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
